---

# The only way to generate a server.properties file is to start Minecraft.
# We send the stop command to the stdin to stop the server right after it
# starts.

- name: generate server.properties
  shell: >
    set -o pipefail && \
      echo "stop" | java -jar {{ minecraft_jar }} nogui
  args:
    creates: server.properties
    chdir: "{{ minecraft_home }}"
    executable: /bin/bash
  become: true

- name: update server.properties
  minecraft_server_file:
    server_file: server-properties
    values: "{{ minecraft_server_properties }}"
    path: "{{ minecraft_home }}/server.properties"
    owner: "{{ minecraft_user }}"
    group: "{{ minecraft_user }}"
  become: true
  notify:
    - restart Minecraft
